// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/automatic-feeders" | "/automatic-feeders/[slug]" | "/baby-monitors" | "/baby-monitors/[slug]" | "/car-seats" | "/car-seats/[slug]" | "/gps-trackers" | "/gps-trackers/[slug]" | "/grooming-tools" | "/grooming-tools/[slug]" | "/high-chairs" | "/high-chairs/[slug]" | "/pet-cameras" | "/pet-cameras/[slug]" | "/strollers" | "/strollers/[slug]"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/automatic-feeders": {}
  "/automatic-feeders/[slug]": { "slug": string; }
  "/baby-monitors": {}
  "/baby-monitors/[slug]": { "slug": string; }
  "/car-seats": {}
  "/car-seats/[slug]": { "slug": string; }
  "/gps-trackers": {}
  "/gps-trackers/[slug]": { "slug": string; }
  "/grooming-tools": {}
  "/grooming-tools/[slug]": { "slug": string; }
  "/high-chairs": {}
  "/high-chairs/[slug]": { "slug": string; }
  "/pet-cameras": {}
  "/pet-cameras/[slug]": { "slug": string; }
  "/strollers": {}
  "/strollers/[slug]": { "slug": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
