// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/automatic-feeders/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/automatic-feeders/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/automatic-feeders/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/automatic-feeders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/automatic-feeders">> = Specific
  const handler = {} as typeof import("../../src/app/automatic-feeders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/baby-monitors/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/baby-monitors/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/baby-monitors/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/baby-monitors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/baby-monitors">> = Specific
  const handler = {} as typeof import("../../src/app/baby-monitors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/car-seats/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/car-seats/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/car-seats/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/car-seats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/car-seats">> = Specific
  const handler = {} as typeof import("../../src/app/car-seats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/gps-trackers/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gps-trackers/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/gps-trackers/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/gps-trackers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gps-trackers">> = Specific
  const handler = {} as typeof import("../../src/app/gps-trackers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/grooming-tools/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/grooming-tools/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/grooming-tools/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/grooming-tools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/grooming-tools">> = Specific
  const handler = {} as typeof import("../../src/app/grooming-tools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/high-chairs/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/high-chairs/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/high-chairs/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/high-chairs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/high-chairs">> = Specific
  const handler = {} as typeof import("../../src/app/high-chairs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pet-cameras/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pet-cameras/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/pet-cameras/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pet-cameras/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pet-cameras">> = Specific
  const handler = {} as typeof import("../../src/app/pet-cameras/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/strollers/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/strollers/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/strollers/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/strollers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/strollers">> = Specific
  const handler = {} as typeof import("../../src/app/strollers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
