// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/air-fryers" | "/air-fryers/[slug]" | "/air-purifiers" | "/air-purifiers/[slug]" | "/automatic-feeders" | "/automatic-feeders/[slug]" | "/baby-monitors" | "/baby-monitors/[slug]" | "/car-seats" | "/car-seats/[slug]" | "/climate-control" | "/climate-control/[slug]" | "/electric-toothbrushes" | "/electric-toothbrushes/[slug]" | "/gps-trackers" | "/gps-trackers/[slug]" | "/grooming-tools" | "/grooming-tools/[slug]" | "/high-chairs" | "/high-chairs/[slug]" | "/massage-guns" | "/massage-guns/[slug]" | "/pet-cameras" | "/pet-cameras/[slug]" | "/robot-vacuums" | "/robot-vacuums/[slug]" | "/security-cameras" | "/security-cameras/[slug]" | "/strollers" | "/strollers/[slug]"
type AppRouteHandlerRoutes = "/api/comments"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/air-fryers": {}
  "/air-fryers/[slug]": { "slug": string; }
  "/air-purifiers": {}
  "/air-purifiers/[slug]": { "slug": string; }
  "/api/comments": {}
  "/automatic-feeders": {}
  "/automatic-feeders/[slug]": { "slug": string; }
  "/baby-monitors": {}
  "/baby-monitors/[slug]": { "slug": string; }
  "/car-seats": {}
  "/car-seats/[slug]": { "slug": string; }
  "/climate-control": {}
  "/climate-control/[slug]": { "slug": string; }
  "/electric-toothbrushes": {}
  "/electric-toothbrushes/[slug]": { "slug": string; }
  "/gps-trackers": {}
  "/gps-trackers/[slug]": { "slug": string; }
  "/grooming-tools": {}
  "/grooming-tools/[slug]": { "slug": string; }
  "/high-chairs": {}
  "/high-chairs/[slug]": { "slug": string; }
  "/massage-guns": {}
  "/massage-guns/[slug]": { "slug": string; }
  "/pet-cameras": {}
  "/pet-cameras/[slug]": { "slug": string; }
  "/robot-vacuums": {}
  "/robot-vacuums/[slug]": { "slug": string; }
  "/security-cameras": {}
  "/security-cameras/[slug]": { "slug": string; }
  "/strollers": {}
  "/strollers/[slug]": { "slug": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
