var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/electric-toothbrushes/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__e8377d44._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_0665c681._.js")
R.c("server/chunks/ssr/[root-of-the-server]__f29fa03c._.js")
R.c("server/chunks/ssr/[root-of-the-server]__6b057281._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__5e876f11._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_electric-toothbrushes_page_actions_eea0ec20.js")
R.m(51228)
module.exports=R.m(51228).exports
